name: Build and deploy
on: [push, workflow_dispatch]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v3
        id: configure_pages
      - uses: paradicms/airtrable-ssg-action@v1-beta
        env:
          NEXT_BASE_PATH: ${{ steps.configure_pages.outputs.base_path }}
        with:
          airtable_base_id: appgU92SdGTwPIVNg
          airtable_access_token: ${{ secrets.AIRTABLE_ACCESS_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
